image: "rust:latest"

stages:
  - lint
  - test

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

fmt:
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

cargo-test:
  stage: test
  script:
    - apt update && apt install -y fuse3 libfuse3-dev
    - cargo build --locked
    - cargo test
    - fallocate -l 256MiB test.bin
    - ./target/debug/redox_installer -c res/test.toml test.bin
